spring.application.name=resource-booking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/resource_booking
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=never
server.error.include-binding-errors=never

app.jwt.secret=change-me-change-me-change-me-change-me-change-me-change-me
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html